name = input()
price = input()
weght = int(input())
coins = int(input())
print(f'{"Чек":=^35}')
print(f'Товар:{name:>29}')
print(f'Цена:{weght:>{19 - len(price)}}кг * {price}руб/кг')
print(f'Итого:{weght * int(price):>26}руб')
print(f'Внесено:{coins:>24}руб')
print(f'Сдача:{coins - weght * int(price):>26}руб')
print(f'{"=":=^35}')
